name: CI
permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.0'
        registry-url: 'https://registry.npmjs.org'

    - uses: volta-cli/action@v4
    - name: Install
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 1
        command: |
          npm i
          npm run update:adapter
          cd ~/
          ls -a
          git add package.json
          git add package-lock.json
          git commit 'update'
          git push

    - name: Versions
      run: |
        node --version
        npm --version
      
