name: CI
permissions: write-all

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.12.0'
        registry-url: 'https://registry.npmjs.org'

    - uses: volta-cli/action@v4
    - name: Install
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 10
        max_attempts: 1
        command: |
          branch=${{ github.ref }}
          echo "Branch: $branch" 
          npm ci
          npm run update:adapter
          echo "GIT DIFF"
          git diff
          echo "---"
          ls -a
          git add . 
          git commit -m 'auto update'
          git config --global user.email "cypress-allure@example.com"
          git config --global user.name "Cypress Allure CI"
          git checkout $branch
          git pull 
          git push origin HEAD:$branch

    - name: Versions
      run: |
        node --version
        npm --version
      
